project:
  type: website
  output-dir: docs

website:
  title: "431-2023"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Calendar"
        href: calendar.qmd
      - text: "Syllabus"
        href: https://thomaselove.github.io/431-syllabus-2023/
      - text: "Course Notes"
        href: https://thomaselove.github.io/431-notes/
      - text: "Assignments"
        href: assignments.qmd
      - text: "Software"
        href: software.qmd
      - text: "Campuswire"
        href: campuswire.qmd
    right:
      - text: "Key Links"
        menu: 
        - text: "Canvas (submissions & recordings)"
          href: https://canvas.case.edu/
        - text: "Shared Google Drive (CWRU)"
          href: https://docs.google.com/document/d/1vtljYk3teBEu_bZWhA7tyaXjZLvqaYqSSMGmCPyHKrM/edit?usp=sharing
        - text: "431-Data page"
          href: https://github.com/THOMASELOVE/431-data
        - text: "431 R packages"
          href: https://github.com/THOMASELOVE/431-packages
        - text: "Minute Papers (Github)"
          href: https://github.com/THOMASELOVE/431-minute-2023
        - text: "Labs (Github)"
          href: https://github.com/THOMASELOVE/431-labs-2023
        - text: "Quizzes (Github)"
          href: https://github.com/THOMASELOVE/431-quizzes-2023
        - text: "Project A Website"
          href: https://thomaselove.github.io/431-projectA-2023/
        - text: "Project B Website"
          href: https://thomaselove.github.io/431-projectB-2023/
        - text: "Class READMEs (Github)"
          href: https://github.com/THOMASELOVE/431-classes-2023
      - text: "Contact Us"
        href: contact.qmd
        
format:
  html:
    theme: zephyr
    css: styles.css
    date-format: iso
    toc: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true

editor: source

