---
title: "431 Fall 2023 Course Calendar"
author: "Thomas E. Love"
date: last-modified
---

## When and Where Do Classes Meet?

All classes meet in person in Room E321-323 in the Robbins Building at the CWRU School of Medicine, from 1:00 to 2:15 PM.

- Each class session is **recorded** via Zoom, and the recordings are then made available for students to view using Canvas. 
- Students attending remotely (for whatever reason) can watch the Zoom as it happens (through [Canvas](https://canvas.case.edu/)), but will not be able to interact with the class during the session.
- Students are expected to attend **at least 20** of the 26 classes during the semester in person.

## Details

- The link for each class is to the README (starting point), which contains key announcements, slides and other links for that session.
- Readings are identified by:
  - **AOS** = David Spiegelhalter's *The Art of Statistics*
  - **R4DS** = Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund, [R for Data Science, 2nd edition](https://r4ds.hadley.nz/)
    - Note that solutions for the exercises in R4DS 2e [are available here](https://mine-cetinkaya-rundel.github.io/r4ds-solutions/).


## December 2023

| LINK | Date | Details |
|:--------:|:--------:|:---------------------------------------------------|
| *Quiz 2 due* | TUE <br /> 12-05 | [Quiz 2](https://github.com/THOMASELOVE/431-quizzes-2023) due at **3 PM**.
| [Class 25](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class25) | TUE <br /> 12-05 | Favorite Movies and AMA Session via Zoom. <br /> **READING** By now, **AOS** complete book
| *min paper* | WED <br /> 12-06 | [Minute Paper after Class 25](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 26](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class26) | THU <br /> 12-07 | Last class. Quiz 2 discussion, and Setting Up 432.
| *Lab Regrade?* | FRI 12-08 | (Optional) Submit [Lab Regrade Request Form](https://bit.ly/431-lab-regrade-form-2023) by noon
| *Presentations* | 12-11 through <br /> 12-14 | [Project B](https://thomaselove.github.io/431-projectB-2023/) Presentations to Dr. Love ([Schedule](https://github.com/THOMASELOVE/431-classes-2023/blob/main/projB/schedule.md)) <br /> 12-11 is Last Day of TA office hours
| *Lab X* | TUE <br /> 12-12 | (Optional) [Lab X](https://thomaselove.github.io/431-labX/) due at Noon.
| *Project B* | SUN <br /> 12-17 | Final [Project B](https://thomaselove.github.io/431-projectB-2023/) All Materials due at **9 AM** (submitted via Canvas, and Google Form)

## Remaining Project B deadlines

- [Project B](https://thomaselove.github.io/431-projectB-2023/) Presentations are scheduled for 12-11 through 12-14. The schedule is [now available](https://github.com/THOMASELOVE/431-classes-2023/blob/main/projB/schedule.md).
- [Project B](https://thomaselove.github.io/431-projectB-2023/) materials are due Sunday 2023-12-17 at **9 AM**.

## August & September 2023

| LINK | Date | Details |
|:--------:|:--------:|:---------------------------------------------------|
| [Class 01](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class01) | TUE <br /> 08-29 | Welcome to 431, How The Course Works <br /> Getting Started with R, RStudio and Quarto
| *survey* | WED <br /> 08-30 | [Welcome to 431 Survey](https://bit.ly/431-2023-welcome-survey) due at Noon
| [Class 02](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class02) | THU <br /> 08-31 | **PART A** begins; see [Course Notes](https://thomaselove.github.io/431-notes/). <br /> Types of Data, Summarizing Quantitative Data
| [Class 03](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class03) | TUE <br /> 09-05 | Visualizing and Managing Data with RStudio and the Tidyverse <br /> **READING** By now, **AOS** Intro & Chapter 1, **R4DS** through Chapter 3 <br /> First Day of TA office hours
| *min paper* | WED <br /> 09-06 | [Minute Paper after Class 03](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 04](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class04) | THU <br /> 09-07 | Describing Quantitative and Categorical Data
| *Lab 1 due* | TUE <br /> 09-12 | [Lab 1](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 05](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class05) | TUE <br /> 09-12 | Visualizing and Describing Data <br /> **READING** By now, **AOS** through Chapter 3, **R4DS** through Chapter 5 and skim 11
| *min paper* | WED <br /> 09-13 | [Minute Paper after Class 05](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 06](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class06) | THU <br /> 09-14 | Visualizations for Comparisons and Associations
| *Lab 2 due* | TUE <br /> 09-19 | [Lab 2](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 07](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class07) | TUE <br /> 09-19 | Visualizing Quantitative Data  <br /> **READING** By now, **AOS** through Chapter 4, **R4DS** Chapters 6-7, 10-11
| [Class 08](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class08) | THU <br /> 09-21 | Categorical Data; Scatterplots, Linear Fits and Power Transformations <br /> Movies Breakout 1
| *Lab 3 due* | TUE <br /> 09-26 | [Lab 3](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 09](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class09) | TUE <br /> 09-26 | Building Confidence Intervals for a Mean or Difference Between Means <br /> **READING** By now, **AOS** through Chapter 5, **R4DS** Chapters 1-7, 10-12
| *min paper* | WED <br /> 09-27 | [Minute Paper after Class 09](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 10](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class10) | THU <br /> 09-28 | Data Management, Wrangling and the Tidyverse with the Movies Data

## October 2023

| LINK | Date | Details |
|:--------:|:--------:|:---------------------------------------------------|
| *Proposal A* | TUE <br /> 10-03 | [Project A Proposal](https://thomaselove.github.io/431-projectA-2023/) due at Noon.
| [Class 11](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class11) | TUE <br /> 10-03 | **PART B** begins; see [Course Notes](https://thomaselove.github.io/431-notes/). <br /> Regression on a Categorical Predictor, Single Imputation <br /> **READING** By now, **AOS** through Chapter 6, **R4DS** Chapters 1-12, 29-30
| *min paper* | WED <br /> 10-04 | [Minute Paper after Class 11](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 12](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class12) | THU <br /> 10-05 | Comparing Means with Paired Samples
| - | THU <br /> 10-05 | [Quiz 1](https://github.com/THOMASELOVE/431-quizzes-2023) made available to you by 5 PM.
| *Quiz 1 due* | TUE <br /> 10-10 | [Quiz 1](https://github.com/THOMASELOVE/431-quizzes-2023) due at Noon. <br /> Quiz 1 covers material from Classes 1-12.
| [Class 13](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class13) | TUE <br /> 10-10 | Comparing Means with Independent Samples <br /> **READING** By now, **AOS** through Chapter 7
| *min paper* | WED <br /> 10-11 | [Minute Paper after Class 13](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 14](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class14) | THU <br /> 10-12 | Comparing Rates and Proportions, 2x2 and Larger Tables
| *Lab 4 due* | TUE <br /> 10-17 | [Lab 4](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 15](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class15) | TUE <br /> 10-17 | Power and Sample Size Considerations <br /> **READING** By now, **AOS** through Chapter 8
| *min paper* | WED <br /> 10-18 | [Minute Paper after Class 15](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 16](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class16) | THU <br /> 10-19 | P values and their problems
| No class | *TUE <br /> 10-24* | CWRU Fall Break. <br /> Now is a great time to work on [Lab X](https://thomaselove.github.io/431-labX/). <br /> No TA office hours 10-23 or 10-24
| *Lab 5 due* | THU <br /> 10-26 | [Lab 5](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 17](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class17) | THU <br /> 10-26 | Catching Up: Miscellaneous Things I Haven't Gotten To Yet <br /> **READING** By now, **AOS** through Chapter 9
| *Project A* | TUE <br /> 10-31 | [Project A Portfolio](https://thomaselove.github.io/431-projectA-2023/) due at Noon. <br /> [Project A](https://thomaselove.github.io/431-projectA-2023/) uses material from Classes 1-12.
| [Class 18](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class18) | TUE <br /> 10-31 | **PART C** begins; see [Course Notes](https://thomaselove.github.io/431-notes/). One-Factor and Two-Factor ANOVA <br /> **READING** By now, **AOS** through Chapter 10, **R4DS** skim Chapters 13-28

## Project A deadlines

- [Project A](https://thomaselove.github.io/431-projectA-2023/) Proposal will be due at noon on Tuesday 2023-10-03. We will provide proposal feedback as soon as possible after that deadline.
- The final [Project A Portfolio](https://thomaselove.github.io/431-projectA-2023/) including the R data set, Quarto and HTML report, video and self-evaluation form are all due at noon on Tuesday 2023-10-31.

## November 2023

| LINK | Date | Details |
|:--------:|:--------:|:---------------------------------------------------|
| *min paper* | WED <br /> 11-01 | [Minute Paper after Class 18](https://github.com/THOMASELOVE/431-minute-2023) due at Noon.
| [Class 19](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class19) | THU <br /> 11-02 | Multiple Regression Modeling, Part 1 
| No class | *TUE <br /> 11-07* | Election Day. (No 431 class but CWRU is open.) <br /> Now is a great time to work on [Lab X](https://thomaselove.github.io/431-labX/).
| *Lab 6 due* | THU <br /> 11-09 | [Lab 6](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 20](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class20) | THU <br /> 11-09 | **ZOOM ONLY** (See email for details) Multiple Regression Modeling, Part 2
| [Class 21](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class21) | TUE <br /> 11-14 | Checking Regression Assumptions, Large Contingency Tables <br /> **READING** By now, **AOS** through Chapter 11
| *Project B* | THU <br /> 11-16 | **CHANGED** [Project B](https://thomaselove.github.io/431-projectB-2023/) [Registration Form](https://bit.ly/431-projB-registration-2023) due at 9 AM.
| [Class 22](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class22) | THU <br /> 11-16 | Using mice to perform multiple imputation, It's All A Linear Model
| No class | *TUE <br /> 11-21* | Thanksgiving week. (No 431 class but CWRU is open.) <br /> No TA office hours 11-19 through 11-25
| No class | *THU <br /> 11-23* | CWRU Thanksgiving Break <br /> No TA office hours 11-19 through 11-25
| *Lab 7* | TUE <br /> 11-28 | [Lab 7](https://github.com/THOMASELOVE/431-labs-2023/tree/main) due at Noon.
| [Class 23](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class23) | TUE <br /> 11-28 | Multiple Regression Modeling, continued <br /> **READING** By now, **AOS** through Chapter 12
| *min paper* | WED <br /> 11-29 | [Minute Paper after Class 23](https://github.com/THOMASELOVE/431-minute-2023) due at **2 PM**.
| [Class 24](https://github.com/THOMASELOVE/431-classes-2023/tree/main/class24) | THU <br /> 11-30 | Some Loose Ends: Power/McNemar/here/77 to NA/ChatGPT, etc.
| - | THU <br /> 11-30 | [Quiz 2](https://github.com/THOMASELOVE/431-quizzes-2023) made available to you by 5 PM. <br /> Quiz 2 covers material from Classes 1-24.

# TA office hours 

TA office hours are held via Zoom, and will begin on **Tuesday 2023-09-05** and will continue through Monday 2023-12-11. They will be held at the following times.

MON | TUE | WED | THU | FRI | SAT | SUN
:------: | :------: | :------: | :------: | :------: | :------: | :------: 
11:40 am <br /> to <br /> 12:40 pm | 5:30 pm <br /> to <br /> 6:30 pm | 11:40 am <br /> to <br /> 12:40 pm | 7:00 pm <br /> to <br /> 8:30 pm | 12:40 pm <br /> to <br /> 2:10 pm | 10:30 am <br /> to <br /> 12 noon | 7:00 pm <br /> to <br /> 8:30 pm
5:00 pm <br /> to <br /> 6:30 pm | - | 7:30 pm <br /> to <br /> 8:30 pm | - | - | 7:00 pm <br /> to <br /> 8:30 pm  | 9:00 pm <br /> to <br /> 10:30 pm
7:00 pm <br /> to <br /> 8:30 pm | - | - | - | - | - | -

Our Shared Google Drive (431 Fall 2023 Dr Love and Students) holds [Zoom](https://cwru.zoom.us/) links for each of these sessions in a document called **TA office hours schedule and Zoom links**. No appointment is necessary. Please just drop in.

- Professor Love will also hold “drop-in hours” for 10 minutes before and for 30 minutes after each class on Tuesdays and Thursdays.
- Office hours are canceled on 2023-10-23 and 2023-10-24 (Fall Break) and from 2023-11-19 through 2023-11-25 (Thanksgiving)

- More information on each of the TAs this semester is found in [this section of our Syllabus](https://thomaselove.github.io/431-syllabus-2023/08_teachingassistants.html).
